INSERT INTO LIEFERANT_PRODUKT VALUES (1, 1);
INSERT INTO LIEFERANT_PRODUKT VALUES (1, 6);
INSERT INTO LIEFERANT_PRODUKT VALUES (2, 7);
INSERT INTO LIEFERANT_PRODUKT VALUES (2, 9);
INSERT INTO LIEFERANT_PRODUKT VALUES (3, 4);
INSERT INTO LIEFERANT_PRODUKT VALUES (3, 11);
commit;