-- Seed-Daten - Tabelle MATERIAL (ASCII only)
SET DEFINE OFF;

INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (1, 'Eiche massiv', 'Massivholz Eiche, selektiert, premium Sortierung, geoelt.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (2, 'Nussbaum massiv', 'Massivholz amerikanischer Nussbaum, dunkel gebeizt, seidenmatt lackiert.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (3, 'Esche massiv', 'Massivholz Esche, feinporig, natur geoelt.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (4, 'Buche massiv', 'Massivholz Buche, gedampft, hart und formstabil.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (5, 'Teak massiv', 'Massivholz Teak, indoor/outdoor geeignet, natur geoelt.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (6, 'Kirschbaum massiv', 'Massivholz Kirschbaum, warmes Farbspiel, klar lackiert.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (7, 'Ahorn massiv', 'Massivholz Ahorn, hell und ruhig, matt lackiert.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (8, 'Raeuchereiche', 'Eiche mit Raeucherung fuer dunkle, edle Optik, geoelt.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (9, 'Ulme massiv', 'Massivholz Ulme, markante Maserung, natur geoelt.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (10, 'Eiche Furnier', 'Echtholzfurnier Eiche auf Traegerplatte, klar lackiert.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (11, 'Nussbaum Furnier', 'Echtholzfurnier Nussbaum, buchbild verleimt, seidenmatt.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (12, 'Makassar Furnier', 'Echtholzfurnier Makassar, kontrastreiche Streifen, hochglanz.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (13, 'Lack hochglanz weiss', 'Mehrschicht-Lackierung, hochglanz, weiss, moebelgeeignet.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (14, 'Lack seidenmatt', 'Robuste Lackoberflaeche, seidenmatt, kratzarm.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (15, 'MDF lackiert', 'MDF Traeger, fein geschichtet, deckend lackiert.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (16, 'HPL Laminat', 'Hochdrucklaminat, sehr strapazierfaehig, pflegeleicht.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (17, 'Fenix NTM', 'Matte Nanotech-Oberflaeche, anti-fingerprint, soft touch.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (18, 'Keramikplatte', 'Technische Keramik, hitze- und kratzbestaendig, 6-12 mm.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (19, 'Sinterstein', 'Sintered Stone, sehr hart, fleckenarm, fuer Tischplatten.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (20, 'Marmor Carrara', 'Naturstein Marmor, hell, klassische Aderung, poliert.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (21, 'Marmor Nero Marquina', 'Schwarzer Marmor mit weisser Aderung, poliert.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (22, 'Travertin', 'Naturstein Travertin, offenporig, gespachtelt und geoe lt.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (23, 'Granit schwarz', 'Granit, sehr robust, satiniert, fuer Arbeits- und Tischplatten.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (24, 'Quarzit', 'Naturstein Quarzit, extrem hart, feine Struktur, matt.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (25, 'Terrazzo', 'Terrazzo Verbundstein mit Natursteinsplit, geschliffen.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (26, 'Glas klar', 'Floatglas klar, geschliffen, optional gehartet.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (27, 'Glas satiniert', 'Satinierte Glasoberflaeche, diffuses Licht, pflegeleicht.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (28, 'Rauchglas', 'Getoentes Glas in Grau, modern, mit UV-Schutz.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (29, 'Spiegelglas', 'Spiegelglas fuer Fronten und Paneele, geschliffen.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (30, 'Edelstahl gebuerstet', 'Edelstahl V2A, gebuerstet, fingerabdruckarm.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (31, 'Edelstahl poliert', 'Edelstahl hochglanz poliert, fuer Akzente und Details.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (32, 'Aluminium eloxiert', 'Aluminium eloxiert, korrosionsbestaendig, fein matt.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (33, 'Messing gebuerstet', 'Messing, gebuerstet, warmes Metallfinish.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (34, 'Bronze patiniert', 'Bronze Optik, patiniert, fuer Griffe und Gestelle.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (35, 'Schwarzstahl pulverbeschichtet', 'Stahl, pulverbeschichtet, robust, matte Struktur.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (36, 'Chrom', 'Chrombeschichtung, spiegelnd, kratzarm bei Pflege.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (37, 'Kupfer gebuerstet', 'Kupfer Finish, gebuerstet, lebendige Patina moeglich.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (38, 'Leder Anilin', 'Offenporiges Anilinleder, sehr weich, natuerliche Narbung.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (39, 'Leder Semi-Anilin', 'Semi-Anilinleder, geschuetzt, hochwertig und pflegeleicht.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (40, 'Leder Nubuk', 'Geschliffenes Leder (Nubuk), samtige Haptik, edel.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (41, 'Leder Vintage', 'Leder mit Pull-up Effekt, entwickelt Patina, charakterstark.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (42, 'Boucle Stoff', 'Boucle Polsterstoff, strukturreich, wohnlich, high-end.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (43, 'Samt Velvet', 'Velours/Samt, dichter Flor, luxurioser Glanz.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (44, 'Leinenmix', 'Leinen-Baumwollmix, atmungsaktiv, natuerliche Optik.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (45, 'Wolle Merino', 'Merinowollstoff, weich, temperaturausgleichend.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (46, 'Performance Stoff', 'Fleckschutz-Polsterstoff, hohe Scheuerfestigkeit.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (47, 'Kaschmirstoff', 'Kaschmiranteil, extrem weich, fuer Premium Polster.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (48, 'Rattan geflochten', 'Natur-Rattan Geflecht, handgeflochten, leicht und stabil.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (49, 'Bambus massiv', 'Bambuslamelle massiv, nachhaltig, sehr formstabil.');
INSERT INTO MATERIAL (MATERIALID, BEZEICHNUNG, BESCHREIBUNG) VALUES (50, 'Kork', 'Korkoberflaeche, warm, schalldaemmend, naturbasiert.');
COMMIT;
