-- Seed-Daten - Tabelle ZAHLUNGSART (ASCII only)
SET DEFINE OFF;

INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (1, 'Barzahlung');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (2, 'EC_Karte');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (3, 'Kreditkarte');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (4, 'Bankueberweisung');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (5, 'Finanzierung');
COMMIT;
