-- Seed-Daten - Tabelle LAGER (ASCII only)
-- Hinweis: BESTELLUNGID und  sind hier absichtlich NULL,
-- damit keine FK-Fehler auftreten (FILIALE hat FK auf LAGER, und BESTELLUNG hat FK auf FILIALE).
-- Nach dem Insert von FILIALE/BESTELLUNG kannst du optional per UPDATE verknuepfen.
SET DEFINE OFF;

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGEN_VERFUEGBAR, LAGERTYP) VALUES (1, NULL, 1250, 'Filiallager');
INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGEN_VERFUEGBAR, LAGERTYP) VALUES (2, NULL, 980, 'Filiallager');
INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGEN_VERFUEGBAR, LAGERTYP) VALUES (3, NULL, 1430, 'Filiallager');
INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGEN_VERFUEGBAR, LAGERTYP) VALUES (4, NULL, 1110, 'Filiallager');
INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGEN_VERFUEGBAR, LAGERTYP) VALUES (5, NULL, 860, 'Filiallager');
INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGEN_VERFUEGBAR, LAGERTYP) VALUES (6, NULL, 5200, 'Zentrallager');
INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGEN_VERFUEGBAR, LAGERTYP) VALUES (7, NULL, 4800, 'Zentrallager');
COMMIT;
