-- Seed-Daten (High-End Möbelhaus) - generiert am 2026-02-05
SET DEFINE OFF;

-- =========================
-- Tabelle: FARBE
-- =========================
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (1, 'F5F1E8', 'Elfenbein matt', 'Elfenbein');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (2, 'F2EFE9', 'Warmweiß seidenmatt', 'Warmweiß');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (3, 'E7E2D3', 'Sandbeige', 'Sandbeige');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (4, 'D8CBB5', 'Kaschmirbeige', 'Kaschmir');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (5, 'CBBBA0', 'Taupe hell', 'Taupe hell');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (6, 'B8A99A', 'Taupe', 'Taupe');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (7, '9C8F86', 'Greige', 'Greige');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (8, '7D746E', 'Graphit-Taupe', 'Graphit-Taupe');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (9, '4B4F52', 'Anthrazit', 'Anthrazit');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (10, '1C1F22', 'Tiefschwarz', 'Tiefschwarz');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (11, 'C2C7C9', 'Silbergrau', 'Silbergrau');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (12, 'AAB2B7', 'Stahlgrau', 'Stahlgrau');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (13, '6E7A83', 'Schieferblau', 'Schieferblau');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (14, '1E3A5F', 'Navy', 'Navy');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (15, '0F5D6D', 'Petrol', 'Petrol');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (16, '0A7A6A', 'Teal', 'Teal');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (17, '1B6B3A', 'Tannengrün', 'Tannengrün');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (18, '2F7D32', 'Smaragdgrün', 'Smaragdgrün');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (19, '6B7F2B', 'Olivgrün', 'Olivgrün');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (20, '9BAE6A', 'Salbeigrün', 'Salbei');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (21, 'E3D7C7', 'Leinen', 'Leinen');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (22, 'D1BFAF', 'Champagner', 'Champagner');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (23, 'C8A56B', 'Honiggold', 'Honiggold');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (24, 'B08D57', 'Messing', 'Messing');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (25, 'A67C52', 'Bronze', 'Bronze');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (26, '8C6B3B', 'Cognac', 'Cognac');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (27, '6F4E37', 'Walnuss', 'Walnuss');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (28, '4E342E', 'Espresso', 'Espresso');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (29, '8B5A2B', 'Karamell', 'Karamell');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (30, 'C19A6B', 'Karamellbeige', 'Karamellbeige');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (31, 'E7B7A3', 'Puderrosa', 'Puderrosa');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (32, 'D9877C', 'Altrosa', 'Altrosa');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (33, 'B76E79', 'Roségold', 'Roségold');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (34, 'B23A48', 'Bordeaux', 'Bordeaux');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (35, '7B1E3A', 'Merlot', 'Merlot');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (36, '6A1B3D', 'Aubergine', 'Aubergine');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (37, '4B2E83', 'Royal-Violett', 'Royal-Violett');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (38, '6D4C41', 'Mokka', 'Mokka');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (39, 'B0A090', 'Stein', 'Stein');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (40, '8F9779', 'Eukalyptus', 'Eukalyptus');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (41, 'D6C7B2', 'Pergament', 'Pergament');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (42, 'F3E5AB', 'Vanille', 'Vanille');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (43, 'E6CDB5', 'Biskuit', 'Biskuit');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (44, 'C0B283', 'Lederbeige', 'Lederbeige');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (45, '9E7E5E', 'Rauchbraun', 'Rauchbraun');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (46, 'C9D1D3', 'Perlgrau', 'Perlgrau');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (47, 'BFD8D2', 'Aqua-Mint', 'Aqua-Mint');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (48, 'F2C14E', 'Safrangelb', 'Safran');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (49, 'D4A017', 'Ockergold', 'Ockergold');
INSERT INTO FARBE (FARBENID, HEXCODE, BESCHREIBUNG, FARBEBEZEICHNUNG) VALUES (50, 'E2725B', 'Terrakotta', 'Terrakotta');
COMMIT;
